"""
src/vector_store.py
-------------------
ChromaDB persistence layer.

Responsibilities:
  - Create / open a ChromaDB persistent collection
  - Upsert question documents + OpenAI-generated embeddings in batches
  - Semantic search (query by text → OpenAI embedding → cosine search)
  - Metadata-filtered fetch (e.g., "all Mid-level Sales questions")
  - Health check

Embeddings are generated by OpenAI text-embedding-3-small,
ensuring a consistent vector space for both indexing and querying.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import List, Optional, Dict, Any

import chromadb
from chromadb.config import Settings

from .config import config
from .embedder import Embedder

logger = logging.getLogger(__name__)

QueryResult = Dict[str, Any]


class VectorStore:
    """
    Wraps a ChromaDB PersistentClient with OpenAI embeddings.

    Usage
    -----
    store = VectorStore()
    store.upsert(ids, documents, embeddings, metadatas)
    results = store.search("How do you handle a difficult client?", top_k=5)
    """

    def __init__(
        self,
        persist_dir: Optional[Path] = None,
        collection_name: Optional[str] = None,
        embedder: Optional[Embedder] = None,
    ):
        self._persist_dir = persist_dir or config.CHROMA_PERSIST_DIR
        self._collection_name = collection_name or config.CHROMA_COLLECTION_NAME
        self._embedder = embedder or Embedder()

        self._persist_dir.mkdir(parents=True, exist_ok=True)

        logger.info(
            "Opening ChromaDB at '%s', collection='%s'",
            self._persist_dir,
            self._collection_name,
        )

        self._client = chromadb.PersistentClient(
            path=str(self._persist_dir),
            settings=Settings(anonymized_telemetry=False),
        )

        self._collection = self._client.get_or_create_collection(
            name=self._collection_name,
            metadata={"hnsw:space": "cosine"},
        )

        logger.info(
            "Collection '%s' ready — %d documents",
            self._collection_name,
            self._collection.count(),
        )

    # ── Properties ────────────────────────────────────────────────

    @property
    def count(self) -> int:
        return self._collection.count()

    @property
    def is_populated(self) -> bool:
        return self._collection.count() > 0

    # ── Write ─────────────────────────────────────────────────────

    def upsert(
        self,
        ids: List[str],
        documents: List[str],
        embeddings: List[List[float]],
        metadatas: List[Dict[str, Any]],
    ) -> None:
        """Upsert a batch of pre-embedded documents (idempotent)."""
        if not ids:
            return
        self._collection.upsert(
            ids=ids,
            documents=documents,
            embeddings=embeddings,
            metadatas=metadatas,
        )
        logger.debug("Upserted %d documents.", len(ids))

    def ingest_questions(self, questions: list, batch_size: int | None = None) -> int:
        """
        Take a list of Question objects, generate OpenAI embeddings, and upsert.

        This is the main ingestion path from Excel → ChromaDB.
        OpenAI text-embedding-3-small generates embeddings for the question corpus.

        Returns total documents upserted.
        """
        bs = batch_size or config.BATCH_SIZE
        total = 0
        batch_ids, batch_docs, batch_meta = [], [], []

        for i, q in enumerate(questions):
            batch_ids.append(q.question_id)
            batch_docs.append(q.to_document())
            batch_meta.append(q.to_metadata())

            if len(batch_ids) == bs:
                print(
                    f"  [OpenAI Embedder] Embedding batch {total // bs + 1} "
                    f"({len(batch_ids)} questions)...", end=" "
                )
                embeddings = self._embedder.encode(batch_docs)
                self.upsert(batch_ids, batch_docs, embeddings, batch_meta)
                total += len(batch_ids)
                print(f"✓ ({total} total)")
                batch_ids, batch_docs, batch_meta = [], [], []

        # Flush remaining
        if batch_ids:
            print(
                f"  [OpenAI Embedder] Embedding final batch "
                f"({len(batch_ids)} questions)...", end=" "
            )
            embeddings = self._embedder.encode(batch_docs)
            self.upsert(batch_ids, batch_docs, embeddings, batch_meta)
            total += len(batch_ids)
            print(f"✓ ({total} total)")

        return total

    # ── Semantic Search ───────────────────────────────────────────

    def search(
        self,
        query_text: str,
        top_k: int | None = None,
        where: Optional[Dict[str, Any]] = None,
    ) -> List[QueryResult]:
        """
        Embed query_text with OpenAI and return the closest questions
        via cosine similarity in ChromaDB.

        This is the RAG retrieval step: the same OpenAI embedding model
        is used for both indexing and querying.

        Parameters
        ----------
        query_text : natural language query (will be embedded by OpenAI)
        top_k      : number of results
        where      : optional ChromaDB metadata filter

        Returns
        -------
        List of dicts: id, document, distance, similarity, metadata
        """
        k = top_k or config.TOP_K
        query_embedding = self._embedder.encode_one(query_text)

        kwargs: Dict[str, Any] = dict(
            query_embeddings=[query_embedding],
            n_results=min(k, self.count) if self.count > 0 else k,
            include=["documents", "distances", "metadatas"],
        )
        if where:
            kwargs["where"] = where

        raw = self._collection.query(**kwargs)
        return self._parse_results(raw)

    def filter_by_metadata(
        self,
        where: Dict[str, Any],
        limit: int = 50,
    ) -> List[QueryResult]:
        """Pure metadata filter — no semantic scoring."""
        raw = self._collection.get(
            where=where,
            limit=limit,
            include=["documents", "metadatas"],
        )
        results = []
        for qid, doc, meta in zip(raw["ids"], raw["documents"], raw["metadatas"]):
            results.append({"id": qid, "document": doc, "metadata": meta})
        return results

    def get_by_id(self, question_id: str) -> Optional[QueryResult]:
        """Retrieve one question by its exact ID."""
        raw = self._collection.get(
            ids=[question_id],
            include=["documents", "metadatas"],
        )
        if not raw["ids"] or not raw["ids"][0]:
            return None
        return {
            "id": raw["ids"][0],
            "document": raw["documents"][0],
            "metadata": raw["metadatas"][0],
        }

    # ── Maintenance ───────────────────────────────────────────────

    def nuke_and_recreate(self) -> None:
        """Drop the collection entirely and recreate empty (for full reloads)."""
        self._client.delete_collection(self._collection_name)
        self._collection = self._client.get_or_create_collection(
            name=self._collection_name,
            metadata={"hnsw:space": "cosine"},
        )
        logger.warning("Collection '%s' dropped and recreated empty.", self._collection_name)

    # ── Helpers ───────────────────────────────────────────────────

    @staticmethod
    def _parse_results(raw: dict) -> List[QueryResult]:
        """Flatten ChromaDB query response into clean list of dicts."""
        results = []
        ids       = raw.get("ids",       [[]])[0]
        docs      = raw.get("documents", [[]])[0]
        distances = raw.get("distances", [[]])[0]
        metas     = raw.get("metadatas", [[]])[0]

        for qid, doc, dist, meta in zip(ids, docs, distances, metas):
            entry: QueryResult = {
                "id": qid,
                "document": doc,
                "distance": round(dist, 4),
                "similarity": round(1 - dist, 4),  # cosine similarity
            }
            if meta:
                entry["metadata"] = meta
                entry.update(meta)
            results.append(entry)

        return results
